# Generated by Django 5.2.17 on 2026-09-09 18:41

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0003_contact_company_primary_contact_contacttype_and_more'),
        ('tenancy', '0002_membership_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('title_is_auto', models.BooleanField(default=False)),
                ('body', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('manual', 'Written in the app'), ('import', 'Created by a CSV import'), ('recording', 'Transcribed from a recording')], default='manual', max_length=16)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='crm.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='crm.contact')),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='crm.importbatch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'note',
                'abstract': False,
                'base_manager_name': 'all_objects',
                'constraints': [models.CheckConstraint(condition=models.Q(('contact__isnull', False), ('company__isnull', False), _negated=True), name='note_not_both_contact_and_company')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
