# Generated by Django 5.2.17 on 2026-09-11 14:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_mail_preference'),
        ('notes', '0001_initial'),
        ('tenancy', '0002_membership_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotePinUnlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(max_length=40)),
                ('unlocked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'note_pin_unlock',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='audio_duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='audio_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.storedfile'),
        ),
        migrations.AddField(
            model_name='note',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='failed_pin_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='pin_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='pin_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='proposed_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='crm.task'),
        ),
        migrations.AddField(
            model_name='note',
            name='summary_state',
            field=models.CharField(choices=[('none', 'No summary'), ('drafting', 'Claude is drafting'), ('proposed', 'Proposed — awaiting review'), ('accepted', 'Accepted'), ('discarded', 'Discarded'), ('failed', 'Drafting failed')], default='none', max_length=16),
        ),
        migrations.AddField(
            model_name='note',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='transcription_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='note',
            name='transcription_operation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='note',
            name='transcription_state',
            field=models.CharField(choices=[('none', 'No recording'), ('uploading', 'Uploading'), ('transcribing', 'Transcribing'), ('done', 'Transcribed'), ('failed', 'Transcription failed')], default='none', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pin_hash__isnull', True), ('pin_set_at__isnull', True)), models.Q(('pin_hash__isnull', False), ('pin_set_at__isnull', False)), _connector='OR'), name='note_pin_hash_and_set_at_together'),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.CheckConstraint(condition=models.Q(('summary__isnull', True), ('summary_state', 'accepted'), _connector='OR'), name='note_summary_only_when_accepted'),
        ),
        migrations.AddField(
            model_name='notepinunlock',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_unlocks', to='notes.note'),
        ),
        migrations.AddField(
            model_name='notepinunlock',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='notepinunlock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='search_vector',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(pin_hash__isnull=True, then=django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('title', config='english', weight='A'), '||', django.contrib.postgres.search.SearchVector('body', config='english', weight='B'), django.contrib.postgres.search.SearchConfig('english')), '||', django.contrib.postgres.search.SearchVector('summary', config='english', weight='B'), django.contrib.postgres.search.SearchConfig('english'))), models.When(then=django.contrib.postgres.search.SearchVector('title', config='english', weight='A'), title_is_auto=False), default=django.db.models.functions.comparison.Cast(models.Value(''), django.contrib.postgres.search.SearchVectorField()), output_field=django.contrib.postgres.search.SearchVectorField()), output_field=django.contrib.postgres.search.SearchVectorField()),
        ),
        # Moved below the generated column it indexes: the autodetector emits
        # generated fields last, so as written this index referenced a column
        # that did not exist yet.
        migrations.AddIndex(
            model_name='note',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='note_search_gin'),
        ),
        migrations.AddIndex(
            model_name='notepinunlock',
            index=models.Index(fields=['note', 'user', 'session_key'], name='note_unlock_lookup'),
        ),
    ]
