# Generated by Django 5.2.17 on 2026-10-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_platform_owner',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
