# Generated by Django 5.2.17 on 2026-10-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_platform_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magiclinktoken',
            name='purpose',
            field=models.CharField(choices=[('signin', 'Sign in'), ('invite', 'Portal invitation'), ('pin_reset', 'Note PIN reset')], default='signin', max_length=16),
        ),
    ]
