# Generated by Django 5.2.17 on 2026-10-08 15:46

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0033_client_invoicing'),
        ('tenancy', '0011_digest_draft_day_and_hour'),
        ('work', '0009_goal_proposal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInvoiceSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_month', models.PositiveSmallIntegerField()),
                ('next_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('lines', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True, db_default='', default='')),
                ('terms', models.TextField(blank=True, db_default='', default='')),
                ('is_active', models.BooleanField(db_default=True, default=True)),
                ('client_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_schedules', to='crm.company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='crm.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'client_invoice_schedule',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClientInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('one_off', 'One-off'), ('recurring', 'Recurring'), ('contact', 'To a contact')], default='one_off', max_length=12)),
                ('number', models.CharField(blank=True, max_length=40, null=True)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready to send'), ('sent', 'Sent'), ('partially_paid', 'Partly paid'), ('paid', 'Paid'), ('void', 'Void')], db_default='draft', default='draft', max_length=16)),
                ('bill_to', models.JSONField(default=dict)),
                ('subtotal_cents', models.BigIntegerField(db_default=0, default=0)),
                ('tax_cents', models.BigIntegerField(db_default=0, default=0)),
                ('total_cents', models.BigIntegerField(db_default=0, default=0)),
                ('paid_cents', models.BigIntegerField(db_default=0, default=0)),
                ('currency', models.CharField(db_default='usd', default='usd', max_length=3)),
                ('notes', models.TextField(blank=True, db_default='', default='')),
                ('terms', models.TextField(blank=True, db_default='', default='')),
                ('pay_instructions', models.TextField(blank=True, db_default='', default='')),
                ('email_to', models.EmailField(blank=True, db_default='', default='', max_length=254)),
                ('email_subject', models.CharField(blank=True, db_default='', default='', max_length=200)),
                ('email_body', models.TextField(blank=True, db_default='', default='')),
                ('pay_url', models.URLField(blank=True, db_default='', default='', max_length=500)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, db_default='', default='')),
                ('client_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='crm.company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='crm.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('outbox_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.outboxmessage')),
                ('pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.storedfile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.clientinvoiceschedule')),
            ],
            options={
                'db_table': 'client_invoice',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClientPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_cents', models.BigIntegerField()),
                ('paid_on', models.DateField()),
                ('method', models.CharField(choices=[('card', 'Card'), ('ach', 'Bank transfer'), ('check', 'Check'), ('wire', 'Wire'), ('other', 'Other')], default='other', max_length=8)),
                ('reference', models.CharField(blank=True, db_default='', default='', max_length=120)),
                ('note', models.TextField(blank=True, db_default='', default='')),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('remove_reason', models.TextField(blank=True, db_default='', default='')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.clientinvoice')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'client_payment',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prefix', models.CharField(db_default='INV-', default='INV-', max_length=12)),
                ('next_value', models.PositiveIntegerField(db_default=1, default=1)),
                ('terms_days', models.PositiveSmallIntegerField(db_default=15, default=15)),
                ('default_notes', models.TextField(blank=True, db_default='', default='')),
                ('default_terms', models.TextField(blank=True, db_default='', default='')),
                ('pay_instructions', models.TextField(blank=True, db_default='', default='')),
                ('email_subject', models.CharField(blank=True, db_default='', default='', max_length=200)),
                ('email_body', models.TextField(blank=True, db_default='', default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'invoice_settings',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClientInvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price_cents', models.BigIntegerField(default=0)),
                ('amount_cents', models.BigIntegerField(default=0)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='work.goal')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.clientinvoice')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='work.project')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'client_invoice_line',
                'ordering': ['position', 'created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_cents__gte', 0), ('quantity__gte', 0), ('unit_price_cents__gte', 0)), name='client_invoice_line_not_negative')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='clientinvoiceschedule',
            constraint=models.CheckConstraint(condition=models.Q(('day_of_month__gte', 1), ('day_of_month__lte', 28)), name='invoice_schedule_day_1_to_28'),
        ),
        migrations.AddIndex(
            model_name='clientinvoice',
            index=models.Index(fields=['tenant', 'status', 'due_date'], name='client_invo_tenant__a2624c_idx'),
        ),
        migrations.AddIndex(
            model_name='clientinvoice',
            index=models.Index(fields=['tenant', 'client_company', '-issue_date'], name='client_invo_tenant__911126_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientinvoice',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='client_invoice_number_unique_per_practice'),
        ),
        migrations.AddConstraint(
            model_name='clientinvoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('client_company__isnull', True), ('kind', 'contact')), models.Q(models.Q(('kind', 'contact'), _negated=True), ('client_company__isnull', False)), _connector='OR'), name='client_invoice_company_unless_contact'),
        ),
        migrations.AddConstraint(
            model_name='clientinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), ('number__isnull', False), _connector='OR'), name='client_invoice_numbered_once_ready'),
        ),
        migrations.AddConstraint(
            model_name='clientinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('paid_cents__gte', 0), ('subtotal_cents__gte', 0), ('tax_cents__gte', 0), ('total_cents__gte', 0)), name='client_invoice_amounts_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='clientinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('paid_cents__lte', models.F('total_cents'))), name='client_invoice_not_overpaid'),
        ),
        migrations.AddConstraint(
            model_name='clientpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='client_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoicesettings',
            constraint=models.UniqueConstraint(fields=('tenant',), name='invoice_settings_one_per_practice'),
        ),
    ]
