# Generated by Django 5.2.17 on 2026-09-15 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_audit_event_acting'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='email_accent_color',
            field=models.CharField(db_default='#F58220', default='#F58220', max_length=7),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_display_name',
            field=models.CharField(blank=True, db_default='Executives Now', default='Executives Now', max_length=80),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_header_color',
            field=models.CharField(db_default='#0A3A65', default='#0A3A65', max_length=7),
        ),
    ]
