# Generated by Django 5.2.17 on 2026-09-15 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_audit_event_acting'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='email_accent_color',
            field=models.CharField(db_default='#52606D', default='#52606D', max_length=7),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_display_name',
            field=models.CharField(blank=True, db_default='', default='', max_length=80),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_header_color',
            field=models.CharField(db_default='#1F2933', default='#1F2933', max_length=7),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.storedfile'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_logo_height',
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_logo_width',
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.storedfile'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_mark_height',
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name='tenant',
            name='email_mark_width',
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
    ]
