# Generated by Django 5.2.17 on 2026-09-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_beta_tenant_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicall',
            name='web_searches',
            field=models.IntegerField(default=0),
        ),
    ]
