# Generated by Django 5.2.17 on 2026-09-29 16:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0007_ai_credits_and_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicall',
            name='input_hash',
            field=models.CharField(blank=True, db_default='', default='', max_length=64),
        ),
        migrations.AddField(
            model_name='aicall',
            name='unattended',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='ai_unattended_daily_cap_usd',
            field=models.DecimalField(db_default=Decimal('5.00'), decimal_places=2, default=Decimal('5.00'), max_digits=10),
        ),
        migrations.AddIndex(
            model_name='aicall',
            index=models.Index(fields=['tenant', 'unattended', 'created_at'], name='ai_call_unattended_day'),
        ),
    ]
