# Generated by Django 5.2.17 on 2026-10-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0008_unattended_ai_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='brand_footer_text',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AddField(
            model_name='tenant',
            name='branding_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('FF', 'Practice owner'), ('CF', 'Associate'), ('VA', 'Assistant'), ('FCC', 'Client owner'), ('ECC', 'Client team member')], max_length=4),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='email_accent_color',
            field=models.CharField(db_default='#7B8794', default='#7B8794', max_length=7),
        ),
    ]
