# Generated by Django 5.2.17 on 2026-10-03 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0009_tenant_brand_footer_text_tenant_branding_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenant',
            name='domain',
            field=models.CharField(blank=True, db_default='', default='', max_length=253),
        ),
        migrations.AddField(
            model_name='tenant',
            name='legal_name',
            field=models.CharField(blank=True, db_default='', default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tenant',
            name='oauth_client',
            field=models.CharField(choices=[('internal', 'Executives Now Workspace'), ('external', 'External')], db_default='internal', default='internal', max_length=12),
        ),
        migrations.AddField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('invited', 'Invited'), ('archived', 'Archived')], db_default='active', default='active', max_length=12),
        ),
    ]
