# Generated by Django 5.2.17 on 2026-10-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0010_tenant_archived_at_tenant_created_by_tenant_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='digest_draft_day',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='tenant',
            name='digest_draft_hour',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        # Carry-over (docs/digest_schedule.md §9): until now every digest was
        # drafted exactly 24 hours before it was sent. Give each existing
        # practice the draft day and hour that reproduce that, so nothing
        # about anyone's schedule moves on the day this is applied. Writes
        # only the two columns added above.
        migrations.RunSQL(
            sql="""
UPDATE "tenant"
   SET "digest_draft_day" = CASE WHEN "digest_send_day" = 1 THEN 7
                                 ELSE "digest_send_day" - 1 END,
       "digest_draft_hour" = "digest_send_hour";
""",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
