# Generated by Django 5.2.17 on 2026-10-05 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0010_tenant_archived_at_tenant_created_by_tenant_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.storedfile'),
        ),
    ]
