# Generated by Django 5.2.17 on 2026-10-09 04:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def switch_on_for_existing(apps, schema_editor):
    """P6 M1-2: every practice that exists today has Bookkeeping. A practice
    made after this is without it until the platform owner switches it on."""
    Tenant = apps.get_model("tenancy", "Tenant")
    PracticeModule = apps.get_model("tenancy", "PracticeModule")
    now = timezone.now()
    for tenant in Tenant.objects.all():
        PracticeModule.objects.get_or_create(
            tenant=tenant, module="bookkeeping", defaults={"enabled_at": now})



class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0011_digest_draft_day_and_hour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(max_length=24)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'practice_module',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'module'), name='practice_module_one_per_module')],
            },
        ),
        migrations.RunPython(switch_on_for_existing, migrations.RunPython.noop),
    ]
