# Generated by Django 5.2.17 on 2026-10-08 17:03

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_client_invoicing'),
        ('crm', '0033_client_invoicing'),
        ('tenancy', '0011_digest_draft_day_and_hour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('bank', 'Bank account'), ('card', 'Credit card'), ('cash', 'Cash')], default='bank', max_length=8)),
                ('last4', models.CharField(blank=True, db_default='', default='', max_length=4)),
                ('opening_balance_cents', models.BigIntegerField(db_default=0, default=0)),
                ('opening_on', models.DateField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'finance_account',
                'ordering': ['kind', 'name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FinanceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('owner', 'Owner'), ('held', 'Held')], max_length=8)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('cpa_code', models.CharField(blank=True, db_default='', default='', max_length=40)),
                ('system_code', models.CharField(blank=True, db_default='', default='', max_length=24)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'finance_category',
                'ordering': ['type', 'position', 'name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FinanceEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer'), ('owner', 'Owner'), ('held', 'Held')], max_length=8)),
                ('direction', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=3)),
                ('on_date', models.DateField(db_index=True)),
                ('amount_cents', models.BigIntegerField()),
                ('description', models.CharField(blank=True, db_default='', default='', max_length=255)),
                ('counterparty', models.CharField(blank=True, db_default='', default='', max_length=160)),
                ('reference', models.CharField(blank=True, db_default='', default='', max_length=120)),
                ('source', models.CharField(choices=[('manual', 'Typed in'), ('invoice', 'From an invoice payment'), ('import', 'From an import')], db_default='manual', default='manual', max_length=8)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('remove_reason', models.TextField(blank=True, db_default='', default='')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.financeaccount')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.financecategory')),
                ('client_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.company')),
                ('client_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_entries', to='billing.clientpayment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries_in', to='finance.financeaccount')),
            ],
            options={
                'db_table': 'finance_entry',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locked_through', models.DateField(blank=True, null=True)),
                ('invoice_income_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.financecategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'finance_settings',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='financecategory',
            constraint=models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('tenant', 'name'), name='finance_category_name_unique_live'),
        ),
        migrations.AddIndex(
            model_name='financeentry',
            index=models.Index(fields=['tenant', 'on_date'], name='finance_ent_tenant__d19b55_idx'),
        ),
        migrations.AddIndex(
            model_name='financeentry',
            index=models.Index(fields=['tenant', 'kind', 'on_date'], name='finance_ent_tenant__ad9cf8_idx'),
        ),
        migrations.AddConstraint(
            model_name='financeentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='finance_entry_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='financeentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account__isnull', False), ('category__isnull', True), ('kind', 'transfer'), ('to_account__isnull', False), models.Q(('account', models.F('to_account')), _negated=True)), models.Q(models.Q(('kind', 'transfer'), _negated=True), ('to_account__isnull', True)), _connector='OR'), name='finance_entry_transfer_shape'),
        ),
        migrations.AddConstraint(
            model_name='financeentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('kind', 'income'), _negated=True), ('direction', 'in'), _connector='OR'), models.Q(models.Q(('kind', 'expense'), _negated=True), ('direction', 'out'), _connector='OR')), name='finance_entry_direction_fits_kind'),
        ),
        migrations.AddConstraint(
            model_name='financeentry',
            constraint=models.UniqueConstraint(condition=models.Q(('client_payment__isnull', False), ('removed_at__isnull', True)), fields=('tenant', 'client_payment', 'kind'), name='finance_entry_one_per_payment_and_kind'),
        ),
        migrations.AddConstraint(
            model_name='financesettings',
            constraint=models.UniqueConstraint(fields=('tenant',), name='finance_settings_one_per_practice'),
        ),
    ]
