# Generated by Django 5.2.17 on 2026-10-08 17:29

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_client_invoicing'),
        ('crm', '0034_import_and_1099'),
        ('finance', '0001_books'),
        ('tenancy', '0011_digest_draft_day_and_hour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('dry_run', 'Dry run'), ('committed', 'Committed'), ('rolled_back', 'Rolled back')], default='dry_run', max_length=12)),
                ('mapping', models.JSONField(default=dict)),
                ('counts', models.JSONField(default=dict)),
                ('last_balance_cents', models.BigIntegerField(blank=True, null=True)),
                ('last_balance_on', models.DateField(blank=True, null=True)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'finance_import_batch',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FinanceImportProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mapping', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'finance_import_profile',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FinanceImportRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField()),
                ('raw', models.JSONField(default=dict)),
                ('on_date', models.DateField(blank=True, null=True)),
                ('amount_cents', models.BigIntegerField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, db_default='', default='', max_length=3)),
                ('description', models.CharField(blank=True, db_default='', default='', max_length=255)),
                ('bank_id', models.CharField(blank=True, db_default='', default='', max_length=120)),
                ('outcome', models.CharField(choices=[('new', 'New entry'), ('duplicate', 'Already in the books'), ('invoice_payment', 'An invoice payment'), ('transfer', 'A transfer'), ('transfer_match', 'The other side of a transfer'), ('ignore', 'Ignored'), ('error', 'Cannot be read')], max_length=16)),
                ('error_text', models.CharField(blank=True, db_default='', default='', max_length=255)),
            ],
            options={
                'db_table': 'finance_import_row',
                'ordering': ['row_number'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FinanceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contains', models.CharField(max_length=120)),
                ('treat_as', models.CharField(choices=[('category', 'A category'), ('transfer', 'A transfer'), ('ignore', 'Ignore')], default='category', max_length=8)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(db_default=True, default=True)),
            ],
            options={
                'db_table': 'finance_rule',
                'ordering': ['position', 'created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='financeentry',
            name='finance_entry_direction_fits_kind',
        ),
        migrations.AddField(
            model_name='financeentry',
            name='bank_id',
            field=models.CharField(blank=True, db_default='', default='', max_length=120),
        ),
        migrations.AddField(
            model_name='financeentry',
            name='payee_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.contact'),
        ),
        migrations.AddConstraint(
            model_name='financeentry',
            constraint=models.CheckConstraint(condition=models.Q(('direction__in', ('in', 'out'))), name='finance_entry_direction_in_or_out'),
        ),
        migrations.AddField(
            model_name='financeimportbatch',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='finance.financeaccount'),
        ),
        migrations.AddField(
            model_name='financeimportbatch',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financeimportbatch',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='financeimportprofile',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='import_profile', to='finance.financeaccount'),
        ),
        migrations.AddField(
            model_name='financeimportprofile',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='financeimportrow',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='finance.financeimportbatch'),
        ),
        migrations.AddField(
            model_name='financeimportrow',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.financecategory'),
        ),
        migrations.AddField(
            model_name='financeimportrow',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='finance.financeentry'),
        ),
        migrations.AddField(
            model_name='financeimportrow',
            name='matched_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_rows', to='finance.financeentry'),
        ),
        migrations.AddField(
            model_name='financeimportrow',
            name='other_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.financeaccount'),
        ),
        migrations.AddField(
            model_name='financeimportrow',
            name='payee_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='financeimportrow',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='financerule',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='finance.financeaccount'),
        ),
        migrations.AddField(
            model_name='financerule',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='finance.financecategory'),
        ),
        migrations.AddField(
            model_name='financerule',
            name='other_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='finance.financeaccount'),
        ),
        migrations.AddField(
            model_name='financerule',
            name='payee_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.contact'),
        ),
        migrations.AddField(
            model_name='financerule',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='financeimportrow',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.financerule'),
        ),
        migrations.AddIndex(
            model_name='financeimportrow',
            index=models.Index(fields=['tenant', 'batch', 'outcome'], name='finance_imp_tenant__b5c7f3_idx'),
        ),
    ]
