# Generated by Django 5.2.17 on 2026-10-09 04:34

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


def mark_contractor_category(apps, schema_editor):
    """The category the starting chart pays contractors from, where a practice
    still has it under that name. Nothing else about any category changes."""
    FinanceCategory = apps.get_model("finance", "FinanceCategory")
    FinanceCategory._base_manager.filter(name="Contractors and associates",
                                         type="expense").update(is_contractor=True)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_import_and_1099'),
        ('tenancy', '0012_practice_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financecategory',
            name='is_contractor',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='financecategory',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.financecategory'),
        ),
        migrations.AddField(
            model_name='financecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='finance.financecategory'),
        ),
        migrations.CreateModel(
            name='FinanceCategoryChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('merge', 'Combined'), ('split', 'Split')], max_length=8)),
                ('entries_moved', models.PositiveIntegerField(default=0)),
                ('first_on', models.DateField(blank=True, null=True)),
                ('last_on', models.DateField(blank=True, null=True)),
                ('contains', models.CharField(blank=True, db_default='', default='', max_length=120)),
                ('by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.financecategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('to_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.financecategory')),
            ],
            options={
                'db_table': 'finance_category_change',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RunPython(mark_contractor_category, migrations.RunPython.noop),
    ]
