# Generated by Django 5.2.17 on 2026-09-09 16:03

import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('industry', models.CharField(blank=True, default='', max_length=120)),
                ('address', models.JSONField(blank=True, null=True)),
                ('is_client_company', models.BooleanField(default=False)),
                ('seat_count', models.PositiveIntegerField(blank=True, null=True)),
                ('digest_ai_prose', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'company',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
