# Generated by Django 5.2.17 on 2026-09-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_contact_referral_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrow',
            name='candidate_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
