# Generated by Django 5.2.17 on 2026-09-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_importrow_candidate_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='gmail_message_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='gmail_thread_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='in_reply_to',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='message_id_header',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='references',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='gmailconnection',
            name='history_id',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='gmailconnection',
            name='last_poll_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='gmailconnection',
            name='send_as_address',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='gmailconnection',
            name='send_as_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='gmailconnection',
            name='send_as_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
