# Generated by Django 5.2.17 on 2026-09-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_emailmessage_gmail_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='value_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importmappingprofile',
            name='value_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importrow',
            name='created_related',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importrow',
            name='preview',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='importrow',
            name='previous_related',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
