# Generated by Django 5.2.17 on 2026-09-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_mail_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxmessage',
            name='producer',
            field=models.CharField(choices=[('stage_rule', 'Stage rule'), ('referral_touch', 'Referral touch'), ('referral_onboarding', 'Referral onboarding'), ('digest', 'Progress digest'), ('strategy_pdf', 'Strategy session PDF'), ('precall_invite', 'Pre-call invite'), ('magic_link', 'Magic link'), ('note_pin_reset', 'Note PIN reset'), ('cadence_change', 'Cadence change'), ('inbound_forward', 'Inbound forward'), ('manual', 'Manual')], db_index=True, max_length=24),
        ),
    ]
