# Generated by Django 5.2.17 on 2026-09-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_client_activity_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxmessage',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('sent', 'Sent'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('suppressed', 'Suppressed (acting as)')], db_index=True, max_length=20),
        ),
    ]
