# Generated by Django 5.2.17 on 2026-09-16 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_outbox_suppressed_state'),
        ('tenancy', '0005_beta_tenant_branding'),
        ('work', '0003_acting_attribution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('goal__isnull', True), ('project__isnull', True), _connector='OR'), name='task_one_parent_not_both'),
        ),
    ]
