# Generated by Django 5.2.17 on 2026-09-18 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_task_one_parent_not_both'),
        ('strategy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source_map_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='strategy.strategymaprow'),
        ),
    ]
