# Generated by Django 5.2.17 on 2026-09-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_task_source_map_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxmessage',
            name='producer',
            field=models.CharField(choices=[('stage_rule', 'Stage rule'), ('referral_touch', 'Referral touch'), ('referral_onboarding', 'Referral onboarding'), ('digest', 'Progress digest'), ('strategy_pdf', 'Strategy session PDF'), ('precall_invite', 'Pre-call invite'), ('magic_link', 'Magic link'), ('note_pin_reset', 'Note PIN reset'), ('client_activity', 'Client activity notice'), ('precall_complete', 'Pre-call form completed'), ('cadence_change', 'Cadence change'), ('inbound_forward', 'Inbound forward'), ('manual', 'Manual')], db_index=True, max_length=24),
        ),
    ]
