# Generated by Django 5.2.17 on 2026-09-23 00:15

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_precall_questions_by_email'),
        ('tenancy', '0006_ai_call_web_searches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailthread',
            name='last_polled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='emailthread',
            name='poll_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('byte_size', models.BigIntegerField(default=0)),
                ('skipped_reason', models.TextField(blank=True, default='')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='crm.emailmessage')),
                ('stored_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.storedfile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'email_attachment',
                'ordering': ['filename'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UnmatchedInbound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='gmail', max_length=16)),
                ('provider_message_id', models.CharField(db_index=True, max_length=255)),
                ('gmail_thread_id', models.CharField(blank=True, default='', max_length=120)),
                ('from_address', models.EmailField(blank=True, default='', max_length=254)),
                ('from_name', models.CharField(blank=True, default='', max_length=200)),
                ('to_addresses', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('body_stripped', models.TextField(blank=True, default='')),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, default='', max_length=120)),
                ('state', models.CharField(choices=[('pending', 'Waiting to be filed'), ('filed', 'Filed'), ('discarded', 'Discarded')], db_index=True, default='pending', max_length=10)),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('filed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('filed_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.contact')),
                ('filed_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.emailmessage')),
                ('filed_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.emailthread')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'unmatched_inbound',
                'ordering': ['-received_at', '-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['tenant', 'state'], name='unmatched_i_tenant__33a573_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'provider', 'provider_message_id'), name='unmatched_inbound_provider_id_unique')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
