# Generated by Django 5.2.17 on 2026-09-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_module6_inbound'),
    ]

    operations = [
        migrations.AddField(
            model_name='stageautomation',
            name='task_client_visible',
            field=models.BooleanField(default=False),
        ),
    ]
