# Generated by Django 5.2.17 on 2026-09-28 21:13

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_enrollment'),
        ('tenancy', '0007_ai_credits_and_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxmessage',
            name='category',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.CreateModel(
            name='EmailSuppression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.EmailField(blank=True, default='', max_length=254)),
                ('category', models.CharField(choices=[('marketing', 'Marketing'), ('updates', 'Updates')], max_length=16)),
                ('source', models.CharField(default='unsubscribe_link', max_length=24)),
                ('lifted_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppressions', to='crm.contact')),
                ('outbox_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.outboxmessage')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'email_suppression',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(condition=models.Q(('contact__isnull', False), ('lifted_at__isnull', True)), fields=('tenant', 'contact', 'category'), name='one_open_suppression_per_contact'), models.UniqueConstraint(condition=models.Q(('contact__isnull', True), ('lifted_at__isnull', True)), fields=('tenant', 'address', 'category'), name='one_open_suppression_per_address')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
