# Generated by Django 5.2.17 on 2026-09-28 21:24

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_email_categories_and_suppression'),
        ('tenancy', '0007_ai_credits_and_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxmessage',
            name='producer',
            field=models.CharField(choices=[('stage_rule', 'Stage rule'), ('referral_touch', 'Referral touch'), ('referral_onboarding', 'Referral onboarding'), ('digest', 'Progress digest'), ('strategy_pdf', 'Strategy session PDF'), ('precall_invite', 'Pre-call invite'), ('precall_questions', 'Pre-call questions by email'), ('magic_link', 'Magic link'), ('note_pin_reset', 'Note PIN reset'), ('client_activity', 'Client activity notice'), ('precall_complete', 'Pre-call form completed'), ('cadence_change', 'Cadence change'), ('inbound_forward', 'Inbound forward'), ('campaign', 'Campaign'), ('manual', 'Manual')], db_index=True, max_length=24),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('sender', models.CharField(blank=True, default='', max_length=254)),
                ('body_mode', models.CharField(choices=[('rich', 'Written in the editor'), ('html', 'Raw HTML')], default='rich', max_length=8)),
                ('body_html', models.TextField(blank=True, default='')),
                ('send_as_is', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'campaign',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ended_reason', models.CharField(blank=True, default='', max_length=16)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='crm.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_recipients', to='crm.contact')),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('outbox_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.outboxmessage')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'campaign_recipient',
                'ordering': ['created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'campaign', 'contact'), name='one_row_per_campaign_recipient')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
