# Generated by Django 5.2.17 on 2026-10-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_campaigns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='referral_touch_mode',
            field=models.CharField(choices=[('ai', 'AI-drafted'), ('template', 'Written by the practice owner')], default='ai', max_length=12),
        ),
    ]
