# Generated by Django 5.2.17 on 2026-10-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_duplicatedismissal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxmessage',
            name='producer',
            field=models.CharField(choices=[('stage_rule', 'Stage rule'), ('referral_touch', 'Referral touch'), ('referral_onboarding', 'Referral onboarding'), ('digest', 'Progress digest'), ('strategy_pdf', 'Strategy session PDF'), ('precall_invite', 'Pre-call invite'), ('precall_questions', 'Pre-call questions by email'), ('magic_link', 'Magic link'), ('note_pin_reset', 'Note PIN reset'), ('client_activity', 'Client activity notice'), ('digest_reminder', 'Digest reminder'), ('precall_complete', 'Pre-call form completed'), ('cadence_change', 'Cadence change'), ('inbound_forward', 'Inbound forward'), ('campaign', 'Campaign'), ('manual', 'Manual'), ('practice_invite', 'Practice invitation'), ('feedback_notice', 'Feedback notice')], db_index=True, max_length=24),
        ),
    ]
