# Generated by Django 5.2.17 on 2026-10-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_client_invoicing'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_1099_payee',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
