# Generated by Django 5.2.17 on 2026-09-22 18:52

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0023_precall_questions_by_email'),
        ('tenancy', '0006_ai_call_web_searches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('web_view_link', models.URLField(blank=True, default='')),
                ('client_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.company')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'meeting',
                'ordering': ['-meeting_date', '-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MeetingProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('proposed_summary', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('summary_discarded', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('partially_actioned', 'Partly actioned'), ('actioned', 'Actioned'), ('rejected', 'Rejected'), ('superseded', 'Superseded by a re-parse')], db_index=True, default='pending', max_length=20)),
                ('ai_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.aicall')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='meetings.meeting')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'meeting_proposal',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='meetings.meetingproposal'),
        ),
        migrations.CreateModel(
            name='MeetingSourceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drive_file_id', models.CharField(db_index=True, max_length=128)),
                ('drive_version', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=120)),
                ('drive_file_owner_email', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('state', models.CharField(choices=[('recorded', 'Recorded'), ('parsing', 'Parsing'), ('parsed', 'Parsed'), ('skipped', 'Skipped'), ('failed', 'Parse failed')], db_index=True, default='recorded', max_length=10)),
                ('skip_reason', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField(blank=True, default='')),
                ('web_view_link', models.URLField(blank=True, default='')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'meeting_source_file',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='meetingproposal',
            name='source_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='meetings.meetingsourcefile'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='source_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='meetings.meetingsourcefile'),
        ),
        migrations.CreateModel(
            name='ProposalItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('participant', 'Participant'), ('action_item', 'Action item'), ('deliverable', 'Deliverable')], db_index=True, max_length=12)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=8)),
                ('source_excerpt', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_record_type', models.CharField(blank=True, default='', max_length=32)),
                ('created_record_id', models.UUIDField(blank=True, null=True)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('actioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='meetings.meetingproposal')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'proposal_item',
                'ordering': ['kind', 'position', 'created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DriveWatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder_id', models.CharField(max_length=128)),
                ('folder_name', models.CharField(blank=True, default='', max_length=255)),
                ('page_token', models.TextField(blank=True, default='')),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'drive_watch',
                'abstract': False,
                'base_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='one_drive_watch_per_tenant')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='crm.contact')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meeting')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'meeting_participant',
                'abstract': False,
                'base_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'meeting', 'contact'), name='one_participant_row_per_meeting')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='meetingsourcefile',
            constraint=models.UniqueConstraint(fields=('tenant', 'drive_file_id', 'drive_version'), name='one_record_per_file_version'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['tenant', '-meeting_date'], name='meeting_tenant__e02950_idx'),
        ),
        migrations.AddIndex(
            model_name='proposalitem',
            index=models.Index(fields=['tenant', 'proposal', 'state'], name='proposal_it_tenant__0b004a_idx'),
        ),
    ]
