# Generated by Django 5.2.17 on 2026-09-22 21:58

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_module5'),
        ('tenancy', '0006_ai_call_web_searches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveBackfill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('now', 'Only new notes from now on'), ('since', 'Also notes since a date'), ('all', 'Everything in the folder')], max_length=8)),
                ('since', models.DateField(blank=True, null=True)),
                ('state', models.CharField(choices=[('declined', 'Starting from now'), ('running', 'Importing'), ('done', 'Imported'), ('cancelled', 'Stopped'), ('failed', 'Stopped by an error')], db_index=True, default='running', max_length=10)),
                ('planned', models.IntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('done', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('after_created_time', models.CharField(blank=True, default='', max_length=40)),
                ('last_error', models.TextField(blank=True, default='')),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backfills', to='meetings.drivewatch')),
            ],
            options={
                'db_table': 'drive_backfill',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['tenant', 'state'], name='drive_backf_tenant__fb222f_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
