# Generated by Django 5.2.17 on 2026-09-28 18:27

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_meetingparticipant_is_practice_and_more'),
        ('tenancy', '0006_ai_call_web_searches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='drivebackfill',
            name='correction_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='drivewatch',
            name='exclusions_seeded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetingsourcefile',
            name='excluded_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='DriveExclusion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pattern', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('seed', 'Set up with the folder'), ('manual', 'Added on the folder card'), ('ignored', 'From “Ignore this file” on a proposal')], default='manual', max_length=8)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='meetings.drivewatch')),
            ],
            options={
                'db_table': 'drive_exclusion',
                'ordering': ['created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DriveWatchFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folder_id', models.CharField(max_length=128)),
                ('folder_name', models.CharField(blank=True, default='', max_length=255)),
                ('depth', models.CharField(choices=[('one', 'This folder and one level down'), ('any', 'This folder and every folder inside it')], default='any', max_length=4)),
                ('name_pattern', models.CharField(blank=True, default='Notes by Gemini', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='meetings.drivewatch')),
            ],
            options={
                'db_table': 'drive_watch_folder',
                'ordering': ['created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='drivebackfill',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backfills', to='meetings.drivewatchfolder'),
        ),
        migrations.AddField(
            model_name='meetingsourcefile',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='meetings.drivewatchfolder'),
        ),
        migrations.AddConstraint(
            model_name='drivewatchfolder',
            constraint=models.UniqueConstraint(fields=('tenant', 'folder_id'), name='one_row_per_watched_folder'),
        ),
    ]
