# Generated by Django 5.2.17 on 2026-09-28 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_watch_folders_and_exclusions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingproposal',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingproposal',
            name='dismissed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingproposal',
            name='dismissed_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='meetingproposal',
            name='dismissed_reason',
            field=models.CharField(blank=True, choices=[('no_meeting', 'No meeting happened'), ('not_relevant', 'Not relevant'), ('vendor_pitch', 'Vendor pitch'), ('other', 'Other')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='meetingproposal',
            name='state_before_dismissal',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='meetingsourcefile',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetingproposal',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending'), ('partially_actioned', 'Partly actioned'), ('actioned', 'Actioned'), ('rejected', 'Rejected'), ('superseded', 'Superseded by a re-parse'), ('dismissed', 'Dismissed')], db_index=True, default='pending', max_length=20),
        ),
    ]
