# Generated by Django 5.2.17 on 2026-09-28 22:40

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_campaigns'),
        ('meetings', '0005_proposal_dismissal'),
        ('tenancy', '0007_ai_credits_and_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_name', models.CharField(blank=True, default='', max_length=255)),
                ('owner_kind', models.CharField(blank=True, default='', max_length=16)),
                ('text', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('follow_up', 'Follow up'), ('record_only', 'Record only'), ('portal', 'Assigned in the portal')], max_length=12)),
                ('source_excerpt', models.TextField(blank=True, default='')),
                ('state', models.CharField(choices=[('open', 'Open'), ('done', 'Done')], db_index=True, default='open', max_length=8)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments', to='crm.company')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments', to='crm.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments', to='meetings.meeting')),
                ('proposal_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='meetings.proposalitem')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitments', to='crm.task')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'commitment',
                'ordering': ['follow_up_date', 'due_date', 'created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['tenant', 'state', 'follow_up_date'], name='commitment_tenant__90fb85_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
