# Generated by Django 5.2.17 on 2026-09-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_commitments'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingsourcefile',
            name='auto_parse_failures',
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
    ]
