# Generated by Django 5.2.17 on 2026-09-18 20:52

import apps.strategy.models
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0020_task_one_parent_not_both'),
        ('tenancy', '0005_beta_tenant_branding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('discipline', models.CharField(default='operations', max_length=40)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('is_default', models.BooleanField(default=False)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'strategy_template',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StrategySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_snapshot', models.JSONField(blank=True, default=dict)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('precall_sent', 'Pre-call form sent'), ('precall_complete', 'Pre-call form complete'), ('in_call', 'In the call'), ('complete', 'Complete'), ('converted', 'Converted to work'), ('lost', 'Lost')], db_index=True, default='draft', max_length=20)),
                ('precall_token_hash', models.CharField(blank=True, default='', max_length=64)),
                ('precall_expires_at', models.DateTimeField(blank=True, null=True)),
                ('proposed_mirror_goal', models.TextField(blank=True, default='')),
                ('proposed_mirror_unlocks', models.TextField(blank=True, default='')),
                ('mirror_goal', models.TextField(blank=True, default='')),
                ('mirror_unlocks', models.TextField(blank=True, default='')),
                ('pdf_include_flags', models.JSONField(blank=True, default=apps.strategy.models.default_pdf_include_flags)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strategy_sessions', to='crm.contact')),
                ('integrator_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.contact')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pdf_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.storedfile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('visionary_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.contact')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='strategy.strategytemplate')),
            ],
            options={
                'db_table': 'strategy_session',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StrategySection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('time_budget_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='strategy.strategytemplate')),
            ],
            options={
                'db_table': 'strategy_section',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StrategyQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=80)),
                ('prompt', models.TextField()),
                ('ask_when', models.CharField(choices=[('precall', 'On the pre-call form'), ('live', 'In the call')], default='live', max_length=8)),
                ('must_ask', models.BooleanField(default=False)),
                ('area', models.CharField(blank=True, default='', max_length=80)),
                ('response_schema', models.CharField(choices=[('free_text', 'Free text'), ('rating_1_10', 'Rating 1–10'), ('diagnostic_triple', 'Said / cause / tried'), ('value_pair', 'Value and why'), ('agreed_note', 'Agreed, with notes'), ('path_reaction', 'Path reaction')], default='free_text', max_length=20)),
                ('is_fractional_observation', models.BooleanField(default=False)),
                ('has_fractional_note', models.BooleanField(default=False)),
                ('is_financial', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='strategy.strategysection')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='strategy.strategytemplate')),
            ],
            options={
                'db_table': 'strategy_question',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StrategyMapRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('bottleneck', models.TextField()),
                ('root_cause', models.TextField(blank=True, default='')),
                ('the_fix', models.TextField(blank=True, default='')),
                ('owner_text', models.CharField(blank=True, default='', max_length=200)),
                ('horizon', models.PositiveSmallIntegerField(blank=True, choices=[(30, '30 days'), (60, '60 days'), (90, '90 days')], null=True)),
                ('measurable', models.CharField(blank=True, default='', max_length=255)),
                ('mechanics_note', models.TextField(blank=True, default='')),
                ('state', models.CharField(choices=[('proposed', 'Proposed by Claude'), ('accepted', 'Accepted onto the map'), ('discarded', 'Discarded')], db_index=True, default='proposed', max_length=10)),
                ('converted_to', models.CharField(blank=True, choices=[('goal', 'A goal'), ('project', 'A project')], default='', max_length=8)),
                ('ai_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.aicall')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_rows', to='strategy.strategysession')),
            ],
            options={
                'db_table': 'strategy_map_row',
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['tenant', 'session', 'position'], name='strategy_ma_tenant__42ee90_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('horizon__isnull', True), ('horizon__in', [30, 60, 90]), _connector='OR'), name='strategy_map_row_horizon_is_30_60_90')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StrategyAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_key', models.CharField(max_length=80)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('fractional_note', models.TextField(blank=True, default='')),
                ('answered_by', models.CharField(choices=[('prospect', 'The prospect, on the pre-call form'), ('fractional', 'The fractional, in the call')], default='fractional', max_length=12)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='strategy.strategysession')),
            ],
            options={
                'db_table': 'strategy_answer',
                'abstract': False,
                'base_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'session', 'question_key'), name='strategy_answer_unique_per_question')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='strategytemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'name', 'version'), name='strategy_template_unique_name_version'),
        ),
        migrations.AddConstraint(
            model_name='strategytemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tenant', 'discipline'), name='strategy_template_one_default_per_discipline'),
        ),
        migrations.AddIndex(
            model_name='strategysession',
            index=models.Index(fields=['tenant', 'state'], name='strategy_se_tenant__0d57ad_idx'),
        ),
        migrations.AddIndex(
            model_name='strategysession',
            index=models.Index(fields=['tenant', 'contact'], name='strategy_se_tenant__ae979c_idx'),
        ),
        migrations.AddConstraint(
            model_name='strategysession',
            constraint=models.UniqueConstraint(condition=models.Q(('precall_token_hash', ''), _negated=True), fields=('tenant', 'precall_token_hash'), name='strategy_session_unique_precall_token'),
        ),
        migrations.AddConstraint(
            model_name='strategysection',
            constraint=models.UniqueConstraint(fields=('tenant', 'template', 'code'), name='strategy_section_unique_code'),
        ),
        migrations.AddIndex(
            model_name='strategyquestion',
            index=models.Index(fields=['tenant', 'section', 'position'], name='strategy_qu_tenant__8cbdd4_idx'),
        ),
        migrations.AddConstraint(
            model_name='strategyquestion',
            constraint=models.UniqueConstraint(fields=('tenant', 'template', 'key'), name='strategy_question_unique_key'),
        ),
    ]
