# Generated by Django 5.2.17 on 2026-09-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0002_seed_operations_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategysession',
            name='drafted_areas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
