# Generated by Django 5.2.17 on 2026-09-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0004_diagnostic_fractional_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategysession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
