# Generated by Django 5.2.17 on 2026-09-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0005_strategysession_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategysession',
            name='current_section',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='strategysession',
            name='current_section_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
