# Generated by Django 5.2.17 on 2026-09-21 19:18

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0006_strategysession_current_section_and_more'),
        ('tenancy', '0005_beta_tenant_branding'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyPathNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(choices=[('a', 'Path A — continue to run it yourself'), ('b', 'Path B — work with the practice')], max_length=1)),
                ('kind', models.CharField(choices=[('pro', 'A pro'), ('con', 'A con')], max_length=3)),
                ('text', models.TextField()),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('state', models.CharField(choices=[('proposed', 'Proposed by Claude'), ('accepted', 'Accepted onto the document'), ('discarded', 'Discarded')], db_index=True, default='proposed', max_length=10)),
                ('from_ai', models.BooleanField(default=True)),
                ('ai_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.aicall')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_notes', to='strategy.strategysession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'strategy_path_note',
                'ordering': ['path', 'kind', 'position', 'created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['tenant', 'session', 'state'], name='strategy_pa_tenant__755431_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
