# Generated by Django 5.2.17 on 2026-09-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0007_path_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategysession',
            name='precall_questions_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
