# Generated by Django 5.2.17 on 2026-09-21 23:52

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0008_precall_questions_by_email'),
        ('tenancy', '0006_ai_call_web_searches'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategySessionPrep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website_url', models.URLField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('bottlenecks', models.JSONField(blank=True, default=list)),
                ('rewordings', models.JSONField(blank=True, default=list)),
                ('state', models.CharField(choices=[('drafting', 'Drafting'), ('ready', 'Ready'), ('failed', 'Failed')], default='drafting', max_length=10)),
                ('ai_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.aicall')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prep', to='strategy.strategysession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'strategy_session_prep',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StrategyPrepQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('why', models.TextField(blank=True, default='')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_pinned', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, default='')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_questions', to='strategy.strategysession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('prep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='strategy.strategysessionprep')),
            ],
            options={
                'db_table': 'strategy_prep_question',
                'ordering': ['position', 'created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='strategysessionprep',
            constraint=models.UniqueConstraint(fields=('tenant', 'session'), name='one_prep_per_session'),
        ),
    ]
