# Generated by Django 5.2.17 on 2026-09-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0009_session_prep'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategysession',
            name='fractional_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='strategysessionprep',
            name='dropped_rewordings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
