# Generated by Django 5.2.17 on 2026-09-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0010_rewording_guard_and_session_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategytemplate',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
