# Generated by Django 5.2.17 on 2026-09-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0011_strategytemplate_archived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyquestion',
            name='ask_if_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='strategysession',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
