# Generated by Django 5.2.17 on 2026-09-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0012_strategyquestion_ask_if_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategymaprow',
            name='merged_from',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
