# Generated by Django 5.2.17 on 2026-09-29 23:30

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0013_strategymaprow_merged_from'),
        ('tenancy', '0008_unattended_ai_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategymaprow',
            name='header',
            field=models.CharField(blank=True, db_default='', default='', max_length=120),
        ),
        migrations.AddField(
            model_name='strategymaprow',
            name='proposed_header',
            field=models.CharField(blank=True, db_default='', default='', max_length=120),
        ),
        migrations.AddField(
            model_name='strategymaprow',
            name='proposed_statement',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AddField(
            model_name='strategymaprow',
            name='statement',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AddField(
            model_name='strategypathnote',
            name='proposed_text',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AddField(
            model_name='strategyquestion',
            name='is_diagnostic_fallback',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='strategytemplate',
            name='format',
            field=models.CharField(choices=[('classic', 'Classic'), ('focused', 'Focused')], db_default='classic', default='classic', max_length=10),
        ),
        migrations.CreateModel(
            name='StrategyDiagnosticProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.CharField(choices=[('lowest_rating', 'One of the two lowest ratings'), ('growth', 'They mentioned growth or expansion'), ('snapshot_gap', 'An evident gap in the Snapshot')], max_length=16)),
                ('basis', models.TextField(blank=True, default='')),
                ('prompt', models.TextField()),
                ('proposed_prompt', models.TextField(blank=True, default='')),
                ('state', models.CharField(choices=[('proposed', 'Proposed by Claude'), ('accepted', 'Accepted into the diagnostic'), ('discarded', 'Discarded')], db_index=True, default='proposed', max_length=10)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('question_key', models.CharField(blank=True, default='', max_length=80)),
                ('ai_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.aicall')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_proposals', to='strategy.strategysession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'strategy_diagnostic_proposal',
                'ordering': ['position', 'created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['tenant', 'session', 'state'], name='strategy_di_tenant__304ed2_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StrategyStyleExample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('map_header', 'Map row header'), ('map_statement', 'Map row focus statement'), ('pro', 'A pro'), ('con', 'A con')], max_length=16)),
                ('proposed', models.TextField()),
                ('accepted', models.TextField()),
                ('source_type', models.CharField(max_length=40)),
                ('source_id', models.UUIDField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'strategy_style_example',
                'ordering': ['-updated_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['tenant', '-updated_at'], name='strategy_st_tenant__d3579a_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'kind', 'source_type', 'source_id'), name='strategy_style_example_one_per_item')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
