# Generated by Django 5.2.17 on 2026-10-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0014_focused_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyanswer',
            name='answered_by',
            field=models.CharField(choices=[('prospect', 'The prospect, on the pre-call form'), ('fractional', 'The practice, in the call')], default='fractional', max_length=12),
        ),
    ]
