# Generated by Django 5.2.17 on 2026-10-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0015_alter_strategyanswer_answered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyquestion',
            name='label',
            field=models.CharField(blank=True, db_default='', default='', max_length=60),
        ),
        migrations.AddField(
            model_name='strategyquestion',
            name='pdf_chip',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='strategysection',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strategysection',
            name='intro',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.AddField(
            model_name='strategysection',
            name='kind',
            field=models.CharField(blank=True, db_default='', default='', max_length=16),
        ),
        migrations.AddField(
            model_name='strategysection',
            name='show_in_pdf',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='strategytemplate',
            name='settings',
            field=models.JSONField(blank=True, db_default={}, default=dict),
        ),
        migrations.AlterField(
            model_name='strategydiagnosticproposal',
            name='rule',
            field=models.CharField(choices=[('lowest_rating', 'One of the two lowest ratings'), ('growth', 'They mentioned growth or expansion'), ('snapshot_gap', 'An evident gap in the Snapshot'), ('precall_gap', 'An evident gap in the pre-call answers'), ('manual', 'Added by hand during the session')], max_length=16),
        ),
        migrations.AlterField(
            model_name='strategytemplate',
            name='format',
            field=models.CharField(choices=[('classic', 'Classic'), ('focused', 'Focused'), ('v3', 'Built in the template builder')], db_default='classic', default='classic', max_length=10),
        ),
    ]
