# Generated by Django 5.2.17 on 2026-10-08 20:30

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_source_file_auto_parse_failures'),
        ('strategy', '0016_template_builder'),
        ('tenancy', '0011_digest_draft_day_and_hour'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='strategymaprow',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategymaprow',
            name='from_call_notes',
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name='strategymaprow',
            name='source_passage',
            field=models.TextField(blank=True, db_default='', default=''),
        ),
        migrations.CreateModel(
            name='StrategyCallNotes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('source', models.CharField(choices=[('meeting_file', 'From the meeting queue'), ('drive', 'A Drive document'), ('pasted', 'Pasted in')], max_length=14)),
                ('title', models.CharField(blank=True, db_default='', default='', max_length=255)),
                ('drive_file_id', models.CharField(blank=True, db_default='', default='', max_length=128)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='call_notes', to='strategy.strategysession')),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='meetings.meetingsourcefile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'strategy_call_notes',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
