# Generated by Django 5.2.17 on 2026-09-11 23:45

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0016_module3_task_engine'),
        ('tenancy', '0002_membership_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Digest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('cadence', models.CharField(choices=[('every_update', 'On every update'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=12)),
                ('state', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('sent', 'Sent'), ('expired', 'Expired unsent'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=10)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('is_stale', models.BooleanField(default=False)),
                ('stale_reason', models.TextField(blank=True, default='')),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('send_window_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digests', to='crm.contact')),
                ('outbox_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.outboxmessage')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'digest',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status_override', models.CharField(blank=True, choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('waiting_on_client', 'Waiting on client'), ('done', 'Done'), ('cancelled', 'Cancelled')], max_length=20, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('client_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.company')),
                ('client_owner_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.contact')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'goal',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status_override', models.CharField(blank=True, choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('waiting_on_client', 'Waiting on client'), ('done', 'Done'), ('cancelled', 'Cancelled')], max_length=20, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('created_by_client', models.BooleanField(default=False)),
                ('client_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.company')),
                ('client_owner_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.contact')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='work.goal')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'project',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('visibility', models.CharField(choices=[('internal', 'Internal only'), ('shared', 'Shared with the client')], default='internal', max_length=8)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.task')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='work.goal')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='work.project')),
            ],
            options={
                'db_table': 'comment',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cadence', models.CharField(choices=[('every_update', 'On every update'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=12)),
                ('is_muted', models.BooleanField(default=False)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholder_rows', to='crm.contact')),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='work.goal')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='work.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='crm.task')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'stakeholder',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StakeholderToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('stakeholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='work.stakeholder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'stakeholder_token',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TaskChecklistItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=500)),
                ('is_done', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='crm.task')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'task_checklist_item',
                'ordering': ['position', 'created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TaskUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status changed'), ('assignee_changed', 'Assignee changed'), ('due_changed', 'Due date changed'), ('comment_added', 'Comment added'), ('checklist_completed', 'Checklist item completed'), ('completed', 'Completed'), ('narrative', 'Narrative added')], max_length=20)),
                ('from_value', models.TextField(blank=True, default='')),
                ('to_value', models.TextField(blank=True, default='')),
                ('client_facing_line', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('user', 'A person'), ('stage_automation', 'Stage automation'), ('meeting_approval', 'Meeting review approval'), ('strategy_conversion', 'Strategy map conversion'), ('system', 'System')], default='user', max_length=20)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('is_client_actor', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='work.goal')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='work.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='crm.task')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'task_update',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DigestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('digest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='work.digest')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('stakeholder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='work.stakeholder')),
                ('task_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digest_items', to='work.taskupdate')),
            ],
            options={
                'db_table': 'digest_item',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='digest',
            index=models.Index(fields=['tenant', 'state', 'send_window_at'], name='digest_tenant__a41b50_idx'),
        ),
        migrations.AddConstraint(
            model_name='digest',
            constraint=models.UniqueConstraint(fields=('tenant', 'contact', 'cadence', 'period_start'), name='digest_unique_per_recipient_period'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['tenant', 'client_company'], name='goal_tenant__8660d6_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['tenant', 'client_company'], name='project_tenant__0965c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('created_by_client', False), ('goal__isnull', True), _connector='OR'), name='project_client_created_has_no_goal'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('task__isnull', False), ('project__isnull', False), ('goal__isnull', False), _connector='OR'), models.Q(models.Q(('project__isnull', False), ('task__isnull', False)), models.Q(('goal__isnull', False), ('task__isnull', False)), models.Q(('goal__isnull', False), ('project__isnull', False)), _connector='OR', _negated=True)), name='comment_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='stakeholder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('goal__isnull', False), ('project__isnull', False), ('task__isnull', False), _connector='OR'), models.Q(models.Q(('goal__isnull', False), ('project__isnull', False)), models.Q(('goal__isnull', False), ('task__isnull', False)), models.Q(('project__isnull', False), ('task__isnull', False)), _connector='OR', _negated=True)), name='stakeholder_exactly_one_level'),
        ),
        migrations.AddConstraint(
            model_name='stakeholder',
            constraint=models.UniqueConstraint(fields=('tenant', 'contact', 'goal'), name='stakeholder_unique_per_goal'),
        ),
        migrations.AddConstraint(
            model_name='stakeholder',
            constraint=models.UniqueConstraint(fields=('tenant', 'contact', 'project'), name='stakeholder_unique_per_project'),
        ),
        migrations.AddConstraint(
            model_name='stakeholder',
            constraint=models.UniqueConstraint(fields=('tenant', 'contact', 'task'), name='stakeholder_unique_per_task'),
        ),
        migrations.AddIndex(
            model_name='taskupdate',
            index=models.Index(fields=['tenant', 'created_at'], name='task_update_tenant__28cc58_idx'),
        ),
        migrations.AddIndex(
            model_name='taskupdate',
            index=models.Index(fields=['tenant', 'task', 'created_at'], name='task_update_tenant__41cdc2_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskupdate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('task__isnull', False), ('project__isnull', False), ('goal__isnull', False), _connector='OR'), models.Q(models.Q(('project__isnull', False), ('task__isnull', False)), models.Q(('goal__isnull', False), ('task__isnull', False)), models.Q(('goal__isnull', False), ('project__isnull', False)), _connector='OR', _negated=True)), name='task_update_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='digestitem',
            constraint=models.UniqueConstraint(fields=('tenant', 'digest', 'task_update'), name='digest_item_unique_per_digest'),
        ),
    ]
