# Generated by Django 5.2.17 on 2026-09-15 14:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_client_activity_producer'),
        ('tenancy', '0002_membership_contact'),
        ('work', '0001_module3_task_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='digest',
            name='digest_unique_per_recipient_period',
        ),
        migrations.AddConstraint(
            model_name='digest',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['expired', 'skipped']), _negated=True), fields=('tenant', 'contact', 'cadence', 'period_start'), name='digest_unique_live_per_recipient_period'),
        ),
    ]
