# Generated by Django 5.2.17 on 2026-09-18 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategy', '0001_initial'),
        ('work', '0003_acting_attribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='baseline_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='baseline_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='direction',
            field=models.CharField(blank=True, choices=[('up_is_good', 'Up is good'), ('down_is_good', 'Down is good')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='goal',
            name='horizon_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='measurable',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='goal',
            name='measurable_unit',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='goal',
            name='source_map_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='strategy.strategymaprow'),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='source_map_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='strategy.strategymaprow'),
        ),
    ]
