# Generated by Django 5.2.17 on 2026-09-21 18:09

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_alter_outboxmessage_producer'),
        ('tenancy', '0005_beta_tenant_branding'),
        ('work', '0004_goal_baseline_at_goal_baseline_value_goal_direction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='how_we_will_know',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='goal',
            name='measurable_kind',
            field=models.CharField(blank=True, choices=[('numeric', 'A number we can track'), ('qualitative', 'A sentence that says how we will know'), ('none', 'Not measurable')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='goal',
            name='outcome_statement',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='GoalNarrative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_body', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
                ('state', models.CharField(choices=[('drafting', 'Drafting'), ('proposed', 'Proposed'), ('accepted', 'Accepted'), ('discarded', 'Discarded'), ('failed', 'Failed')], default='proposed', max_length=12)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ai_call', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenancy.aicall')),
                ('goal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='narrative', to='work.goal')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'goal_narrative',
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GoalNarrativeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrative_versions', to='work.goal')),
                ('narrative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='work.goalnarrative')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'goal_narrative_version',
                'ordering': ['-accepted_at', '-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GoalReportExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='crm.company')),
                ('exported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='work.goal')),
                ('narrative_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='work.goalnarrativeversion')),
                ('stored_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.storedfile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'goal_report_export',
                'ordering': ['-exported_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GoalResolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolution', models.CharField(choices=[('achieved', 'Achieved'), ('changed_course', 'Changed course'), ('paused', 'Paused'), ('retired', 'Retired'), ('resumed', 'Resumed')], max_length=20)),
                ('reason', models.TextField()),
                ('resolved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='work.goal')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'goal_resolution',
                'ordering': ['-resolved_at', '-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GoalMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('measured_at', models.DateField()),
                ('note', models.TextField(blank=True, default='')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='work.goal')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'goal_measurement',
                'ordering': ['-measured_at', '-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['tenant', 'goal', '-measured_at'], name='goal_measur_tenant__f2c83d_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GoalMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('occurred_at', models.DateField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='work.goal')),
                ('source_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='crm.task')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'goal_milestone',
                'ordering': ['position', 'due_date', 'created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'source_task'), name='one_milestone_per_task')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='goalnarrative',
            constraint=models.UniqueConstraint(fields=('tenant', 'goal'), name='one_living_narrative_per_goal'),
        ),
        migrations.AddIndex(
            model_name='goalnarrativeversion',
            index=models.Index(fields=['tenant', 'goal', '-accepted_at'], name='goal_narrat_tenant__b66d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='goalreportexport',
            index=models.Index(fields=['tenant', 'client_company', '-exported_at'], name='goal_report_tenant__2cde3c_idx'),
        ),
        migrations.AddConstraint(
            model_name='goalresolution',
            constraint=models.CheckConstraint(condition=models.Q(('reason', ''), _negated=True), name='goal_resolution_reason_not_blank'),
        ),
    ]
