# Generated by Django 5.2.17 on 2026-10-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_module_4b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digest',
            name='state',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('sent', 'Sent'), ('late', 'Not sent on time'), ('expired', 'Expired unsent'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=10),
        ),
    ]
