# Generated by Django 5.2.17 on 2026-10-08 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0006_digest_state_late'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='project_client_created_has_no_goal',
        ),
    ]
