# Generated by Django 5.2.17 on 2026-10-08 02:10

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_outbox_producer_digest_reminder'),
        ('tenancy', '0011_digest_draft_day_and_hour'),
        ('work', '0007_client_project_under_goal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyGoalOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.JSONField(default=list)),
                ('client_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crm.company')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_goal_order',
                'abstract': False,
                'base_manager_name': 'all_objects',
                'constraints': [models.UniqueConstraint(fields=('tenant', 'client_company'), name='company_goal_order_one_per_company')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='GoalOrderProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.JSONField(default=list)),
                ('note', models.TextField(blank=True, default='')),
                ('state', models.CharField(choices=[('pending', 'Waiting for the practice'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('superseded', 'Replaced by a newer proposal')], default='pending', max_length=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('client_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crm.company')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'goal_order_proposal',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['tenant', 'client_company', 'state'], name='goal_order__tenant__f98935_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'pending')), fields=('tenant', 'client_company'), name='goal_order_proposal_one_pending_per_company')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
