# Generated by Django 5.2.17 on 2026-10-08 02:16

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_outbox_producer_digest_reminder'),
        ('tenancy', '0011_digest_draft_day_and_hour'),
        ('work', '0008_goal_priority_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('why', models.TextField(blank=True, default='')),
                ('state', models.CharField(choices=[('pending', 'Waiting for the practice'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('client_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crm.company')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='work.goal')),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'goal_proposal',
                'ordering': ['-created_at'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'indexes': [models.Index(fields=['tenant', 'client_company', 'state'], name='goal_propos_tenant__1d8678_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='goal_proposal_title_not_blank')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
